### ISSUE TITLE
执行pip install -r requirements.txt时报错

### ISSUE THREAD

**Issue by BeiMianNa** [codefuse-ai/Test-Agent#10]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3'
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\33\AppData\Local\Temp\pip-install-7rd2r2v0\deepspeed_0aefcc0fcaa04450b49543c945a2152f\setup.py", line 182, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\33\AppData\Local\Temp\pip-install-7rd2r2v0\deepspeed_0aefcc0fcaa04450b49543c945a2152f\setup.py", line 52, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hailianzhl** [comment]
我们刚刚更新了requirements.txt文件，可以重新尝试下
