### ISSUE TITLE
无法加载模型

### ISSUE THREAD

**Issue by yizhuying** [codefuse-ai/Test-Agent#2]
模型是在https://modelscope.cn/models/codefuse-ai/TestGPT-7B/files clone的

<img width="1284" alt="image" src="https://github.com/codefuse-ai/Test-Agent/assets/122763218/bd4d5767-8f1b-4d41-bd33-b10d16b47930">

**Comment by pandaDevs** [comment]
可以先确认下下载的模型是不是完整的，比如下载的模型文件大小与modelscope上的是否一致

**Comment by yizhuying** [comment]
完整的，文件大小一致的

**Comment by yizhuying** [comment]
我这边是英伟达A40显卡，有影响吗

**Comment by yizhuying** [comment]
经过验证，本地MacBook可以正常启动，服务器英伟达A40显卡，不能启动，报错入上图

**Comment by mcc202307** [comment]
@ZeroBugHero  有更多的报错信息吗，参考这个排查下  https://blog.csdn.net/zchoney/article/details/104059143?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-104059143-blog-119681583.235%5Ev38%5Epc_relevant_anti_vip_base&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-104059143-blog-119681583.235%5Ev38%5Epc_relevant_anti_vip_base&utm_relevant_index=2

目前报错信息只能看到进程被 “killed”了

**Comment by yizhuying** [comment]
<img width="1266" alt="image" src="https://github.com/codefuse-ai/Test-Agent/assets/122763218/c8f31e41-03c5-4f1b-8606-15913f167a85">
@mcc202307

**Comment by yizhuying** [comment]
解决了，16G内容不够使用
