### ISSUE TITLE
无法发送信息

### ISSUE THREAD

**Issue by jiuceng1** [codefuse-ai/Test-Agent#3]
部署完成，发送信息提示NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

**Comment by jiuceng1** [comment]
![image](https://github.com/codefuse-ai/Test-Agent/assets/97685947/1323fb14-2d63-40dd-826f-08c3cde00d34)

**Comment by PerryYu** [comment]
需要确认下模型是否启动成功，可以把前序的几个步骤的控制台日志贴一下，以及完整的页面截图也一并提供，然后需要确保硬件有14GB左右的显存
