### ISSUE TITLE
尝试用windows安装时，报错

### ISSUE THREAD

**Issue by lingfengji** [codefuse-ai/Test-Agent#6]
请问当前的这个模型是不支持windows吗？

使用windows安装环境时报错，uvloop报错不支持windows系统
![image](https://github.com/codefuse-ai/Test-Agent/assets/40734742/96d108de-474f-4ad4-b7e0-8860c1295035)

**Comment by pandaDevs** [comment]
支持windows，但有些库可能在windows上装不了。比如这个uvloop，可以跳过不安装
