### ISSUE TITLE
请问，模型有办法调优一下吗？我台式机是15G显存，聊一句就超了。。。

### ISSUE THREAD

**Issue by lingfengji** [codefuse-ai/Test-Agent#8]
可以配置什么参数之类的，可以降低性能要求？
![image](https://github.com/codefuse-ai/Test-Agent/assets/40734742/88b6db3f-171a-4231-9e6e-baf4bca6c36d)

**Comment by hailianzhl** [comment]
暂时没有哈。我们后续会逐步开源量化版本，欢迎关注
